name: CI

on: [push, pull_request]

jobs:
  build:
    # Usually I use ubuntu-latest but there were some errors when testing with it.
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run test:ci
